basePath: /
host: localhost:8000
info:
  contact: {}
  description: todo app for test
  title: ToDo App Api
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
